/**
 * Eurosign
 * This is the documentation of the eurosign API, you can download all of our SDK in this page.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eurosign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body1 model module.
* @module Eurosign/model/Body1
* @version 1.0.0
*/
export default class Body1 {
    /**
    * Constructs a new <code>Body1</code>.
    * @alias module:Eurosign/model/Body1
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Eurosign/model/Body1} obj Optional instance to populate.
    * @return {module:Eurosign/model/Body1} The populated <code>Body1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body1();
                        
            
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], 'String');
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'String');
            }
            if (data.hasOwnProperty('recipientsOrder')) {
                obj['recipientsOrder'] = ApiClient.convertToType(data['recipientsOrder'], 'Boolean');
            }
            if (data.hasOwnProperty('recipients')) {
                obj['recipients'] = ApiClient.convertToType(data['recipients'], 'String');
            }
        }
        return obj;
    }

    /**
    * The base64 encoded file
    * @member {String} file
    */
    file = undefined;
    /**
    * The signature request expiration date (format Y-m-d H:i:s)
    * @member {String} expirationDate
    */
    expirationDate = undefined;
    /**
    * If true, recipients will receive the signature request ordered by their index
    * @member {Boolean} recipientsOrder
    */
    recipientsOrder = undefined;
    /**
    *  The array containing signature request recipients
    * @member {String} recipients
    */
    recipients = undefined;




}
