/**
 * Eurosign
 * This is the documentation of the eurosign API, you can download all of our SDK in this page.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eurosign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Eurosign);
  }
}(this, function(expect, Eurosign) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Eurosign.InlineResponse2001();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001', function() {
    it('should create an instance of InlineResponse2001', function() {
      // uncomment below and update the code to test InlineResponse2001
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be.a(Eurosign.InlineResponse2001);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property senderId (base name: "senderId")', function() {
      // uncomment below and update the code to test the property senderId
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creationDate")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property sendDate (base name: "sendDate")', function() {
      // uncomment below and update the code to test the property sendDate
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property expirationDate (base name: "expirationDate")', function() {
      // uncomment below and update the code to test the property expirationDate
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property recipientsOrder (base name: "recipientsOrder")', function() {
      // uncomment below and update the code to test the property recipientsOrder
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property currentRecipientIndex (base name: "currentRecipientIndex")', function() {
      // uncomment below and update the code to test the property currentRecipientIndex
      //var instane = new Eurosign.InlineResponse2001();
      //expect(instance).to.be();
    });

  });

}));
