/**
 * Eurosign
 * This is the documentation of the eurosign API, you can download all of our SDK in this page.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eurosign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Eurosign);
  }
}(this, function(expect, Eurosign) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Eurosign.SignatureRequestsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SignatureRequestsApi', function() {
    describe('cancelSignatureRequests', function() {
      it('should call cancelSignatureRequests successfully', function(done) {
        //uncomment below and update the code to test cancelSignatureRequests
        //instance.cancelSignatureRequests(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createSignatureRequest', function() {
      it('should call createSignatureRequest successfully', function(done) {
        //uncomment below and update the code to test createSignatureRequest
        //instance.createSignatureRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSignatureRequest', function() {
      it('should call getSignatureRequest successfully', function(done) {
        //uncomment below and update the code to test getSignatureRequest
        //instance.getSignatureRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSignatureRequestAuditTrail', function() {
      it('should call getSignatureRequestAuditTrail successfully', function(done) {
        //uncomment below and update the code to test getSignatureRequestAuditTrail
        //instance.getSignatureRequestAuditTrail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSignatureRequestRecipient', function() {
      it('should call getSignatureRequestRecipient successfully', function(done) {
        //uncomment below and update the code to test getSignatureRequestRecipient
        //instance.getSignatureRequestRecipient(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSignatureRequestRecipients', function() {
      it('should call getSignatureRequestRecipients successfully', function(done) {
        //uncomment below and update the code to test getSignatureRequestRecipients
        //instance.getSignatureRequestRecipients(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSignatureRequests', function() {
      it('should call getSignatureRequests successfully', function(done) {
        //uncomment below and update the code to test getSignatureRequests
        //instance.getSignatureRequests(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendSignatureRequest', function() {
      it('should call sendSignatureRequest successfully', function(done) {
        //uncomment below and update the code to test sendSignatureRequest
        //instance.sendSignatureRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSignatureRequest', function() {
      it('should call updateSignatureRequest successfully', function(done) {
        //uncomment below and update the code to test updateSignatureRequest
        //instance.updateSignatureRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
